export const catalogo = [
    {
        id: 1,
        marca: 'Zara',
        nome: 'Camisa Larga com Bolsos',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-1.jpg',
        feminino: false,
    },
    {
        id: 2,
        marca: 'Zara',
        nome: 'Casaco Reto com Lã',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-2.jpg',
        feminino: true,
    },
    {
        id: 3,
        marca: 'Zara',
        nome: 'Jaqueta com Efeito Camurça',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-3.jpg',
        feminino: false,
    },
    {
        id: 4,
        marca: 'Zara',
        nome: 'Sobretudo em Mescla de Lã',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-4.jpg',
        feminino: false,
    },
    {
        id: 5,
        marca: 'Zara',
        nome: 'Camisa Larga Acolchoada de Veludo Cotelê',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-5.jpg',
        feminino: false,
    },
    {
        id: 6,
        marca: 'Zara',
        nome: 'Casaco de Lã com Botões',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-6.jpg',
        feminino: true,
    },
    {
        id: 7,
        marca: 'Zara',
        nome: 'Casaco com Botões',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-7.jpg',
        feminino: true,
    },
    {
        id: 8,
        marca: 'Zara',
        nome: 'Colete Comprido com Cinto',
        preco: "R$ 699,99",
        promocional: "R$299,99",
        imagem: 'product-8.jpg',
        feminino: true,
    },
];